"""Realistic mock data for GoogleMart Virtual Chef."""

PRODUCTS = {
    "SKU_MILK_FULL": {
        "name": "Full Cream Milk 2L",
        "price": 3.10,
        "macros": {"protein": 3.4, "carbs": 4.8, "fat": 3.4},
        "allergens": ["dairy"],
        "image_keyword": "milk,bottle,full-cream",
        "image_url": "/static/milk_bottle.png",
    },
    "SKU_BREAD_WHITE": {
        "name": "White Sandwich Bread 700g",
        "price": 2.70,
        "macros": {"protein": 7.5, "carbs": 45, "fat": 1.5},
        "allergens": ["gluten"],
        "image_keyword": "white,bread,loaf",
        "image_url": "/static/white_bread.png",
    },
    "SKU_EGGS_FREE": {
        "name": "Free Range Large Eggs 12pk 700g",
        "price": 5.50,
        "macros": {"protein": 12.6, "carbs": 0.7, "fat": 9.5},
        "allergens": ["eggs"],
        "image_keyword": "eggs,carton",
        "image_url": "/static/eggs_carton.png",
    },
    "SKU_CHICKEN_BREAST": {
        "name": "Chicken Breast Fillet 1kg",
        "price": 14.50,
        "macros": {"protein": 31, "carbs": 0, "fat": 3.6},
        "allergens": [],
        "image_keyword": "chicken,breast,raw",
        "image_url": "/static/chicken_breast.png",
    },
    "SKU_BANANAS_KG": {
        "name": "Bananas 1kg",
        "price": 4.50,
        "macros": {"protein": 1.1, "carbs": 23, "fat": 0.3},
        "allergens": [],
        "image_keyword": "bananas,bunch",
        "image_url": "/static/bananas_bunch.png",
    },
    "SKU_AVOCADO_EACH": {
        "name": "Hass Avocado Each",
        "price": 1.50,
        "macros": {"protein": 2, "carbs": 8.5, "fat": 15},
        "allergens": [],
        "image_keyword": "avocado,hass",
        "image_url": "/static/avocado_hass.png",
    },
    "SKU_MINCE_BEEF": {
        "name": "Beef Mince Typical Fat 500g",
        "price": 8.50,
        "macros": {"protein": 20, "carbs": 0, "fat": 15},
        "allergens": [],
        "image_keyword": "beef,mince,raw",
        "image_url": "/static/beef_mince.png",
    },
    "SKU_PASTA_PENNE": {
        "name": "Penne Pasta 500g",
        "price": 1.30,
        "macros": {"protein": 12, "carbs": 71, "fat": 1.5},
        "allergens": ["gluten"],
        "image_keyword": "penne,pasta,dry",
        "image_url": "/static/penne_pasta.png",
    },
    "SKU_TOMATO_SAUCE": {
        "name": "Tomato Pasta Sauce 500g",
        "price": 2.20,
        "macros": {"protein": 1.5, "carbs": 7, "fat": 0.5},
        "allergens": [],
        "image_keyword": "tomato,sauce,jar",
        "image_url": "/static/tomato_sauce.png",
    },
    "SKU_CHEESE_BLOCK": {
        "name": "Tasty Cheese Block 500g",
        "price": 7.50,
        "macros": {"protein": 25, "carbs": 1, "fat": 33},
        "allergens": ["dairy"],
        "image_keyword": "cheddar,cheese,block",
        "image_url": "/static/cheese_block.png",
    },
    "SKU_APPLES_PINK": {
        "name": "Pink Lady Apples 1kg Pack",
        "price": 5.50,
        "macros": {"protein": 0.3, "carbs": 14, "fat": 0.2},
        "allergens": [],
        "image_keyword": "apples,pink-lady",
        "image_url": "/static/apples_pack.png",
    },
    "SKU_GARLIC_EACH": {
        "name": "Garlic Loose Each",
        "price": 0.80,
        "macros": {},
        "allergens": [],
        "image_keyword": "garlic,bulb",
        "image_url": "/static/garlic_bulb.png",
    },
    "SKU_SALMON": {
        "name": "Fresh Salmon Fillets 200g",
        "price": 8.40,
        "macros": {"protein": 20, "carbs": 0, "fat": 13},
        "allergens": ["fish"],
        "image_keyword": "salmon,fillet",
        "image_url": "/static/salmon_fillet.png",
    },
    "SKU_LEMON": {
        "name": "Fresh Lemon Each",
        "price": 1.03,
        "macros": {},
        "allergens": [],
        "image_keyword": "lemon",
        "image_url": "/static/lemon.png",
    },
    "SKU_ASPARAGUS": {
        "name": "Fresh Green Asparagus Bunch",
        "price": 4.50,
        "macros": {},
        "allergens": [],
        "image_keyword": "asparagus,bunch",
        "image_url": "/static/asparagus.png",
    },
    "SKU_ONION": {
        "name": "Brown Onion Each",
        "price": 0.36,
        "macros": {},
        "allergens": [],
        "image_keyword": "onion,brown",
        "image_url": "/static/onion.png",
    },
    "SKU_OLIVE_OIL": {
        "name": "Extra Virgin Olive Oil 500ml",
        "price": 9.00,
        "macros": {},
        "allergens": [],
        "image_keyword": "olive,oil,bottle",
        "image_url": "/static/olive_oil.png",
    },
    "SKU_BROCCOLI": {
        "name": "Fresh Broccoli Each",
        "price": 1.95,
        "macros": {},
        "allergens": [],
        "image_keyword": "broccoli",
        "image_url": "/static/broccoli.png",
    },
    "SKU_SPAGHETTI": {
        "name": "Spaghetti 500g",
        "price": 1.00,
        "macros": {"protein": 12, "carbs": 71, "fat": 1.5},
        "allergens": ["gluten"],
        "image_keyword": "spaghetti,pasta",
        "image_url": "/static/spaghetti.png",
    },
    "SKU_TORTILLA_CHIPS": {
        "name": "Tortilla Chips 200g",
        "price": 3.50,
        "macros": {},
        "allergens": [],
        "image_keyword": "tortilla,chips",
        "image_url": "/static/tortilla_chips.png",
    },
    "SKU_BAGELS": {
        "name": "Plain Bagels 4 Pack",
        "price": 3.50,
        "macros": {},
        "allergens": ["gluten"],
        "image_keyword": "bagels",
        "image_url": "/static/bagels.png",
    },
    "SKU_SOURDOUGH": {
        "name": "Sourdough Loaf",
        "price": 7.00,
        "macros": {},
        "allergens": ["gluten"],
        "image_keyword": "sourdough,bread",
        "image_url": "/static/sourdough_loaf.png",
    },
}

RECIPES = [
    {
        "name": "Creamy Garlic Chicken Pasta",
        "ingredients": [
            "SKU_CHICKEN_BREAST",
            "SKU_PASTA_PENNE",
            "SKU_GARLIC_EACH",
            "SKU_MILK_FULL", # Fallback for cream if not available
        ],
        "optional_ingredients": ["SKU_CHEESE_BLOCK"],
        "instructions": "Cook pasta. Sear chicken. Add garlic and milk/cream. Mix with pasta.",
    },
    {
        "name": "Classic Bolognese",
        "ingredients": ["SKU_MINCE_BEEF", "SKU_PASTA_PENNE", "SKU_GARLIC_EACH", "SKU_TOMATO_SAUCE"],
        "optional_ingredients": ["SKU_CHEESE_BLOCK"],
        "instructions": "Brown beef with garlic. Simmer with sauce. Serve over pasta.",
    },
    {
        "name": "Pan-Seared Salmon",
        "ingredients": ["SKU_SALMON", "SKU_LEMON", "SKU_ASPARAGUS"],
        "optional_ingredients": ["SKU_OLIVE_OIL"],
        "instructions": "Sear salmon in a pan. Serve with lemon and grilled asparagus.",
    },
    {
        "name": "Spaghetti Bolognese",
        "ingredients": ["SKU_MINCE_BEEF", "SKU_SPAGHETTI", "SKU_TOMATO_SAUCE", "SKU_ONION", "SKU_GARLIC_EACH", "SKU_OLIVE_OIL"],
        "optional_ingredients": ["SKU_CHEESE_BLOCK"],
        "instructions": "Sauté onion and garlic in olive oil. Add beef and brown. Add sauce and simmer. Serve over spaghetti.",
    },
    {
        "name": "Grilled Chicken with Broccoli",
        "ingredients": ["SKU_CHICKEN_BREAST", "SKU_BROCCOLI", "SKU_OLIVE_OIL"],
        "optional_ingredients": [],
        "instructions": "Grill chicken and broccoli with olive oil.",
    },
]

MOCK_CART = [
    "SKU_CHICKEN_BREAST",
    "SKU_PASTA_PENNE",
    "SKU_GARLIC_EACH",
]
